package com.homesfresh.util

object SharedPreferenceKey {
    var IsLoggedIn = "false"
    var LOCATION_ID = "LOCATION_ID"
    var FIREBASE_ID = "FIREBASE_ID"
    var USER_ID = "USER_ID"
    var USER_NAME = "USER_NAME"
    var USER_PROFILE_IMAGE = "USER_PROFILE_IMAGE"
    var USER_ADDRESS = "USER_ADDRESS"
    var USER_EMAIL = "USER_EMAIL"
    var USER_MOBILE = "USER_MOBILE"
    var IS_ADDRESS_AVAILABLE = "IS_ADDRESS_AVAILABLE"
    var CART_COUNT="CART_COUNT"
    var NOTIFICATION_COUNT="NOTIFICATION_COUNT"
    var LAST_PLACE_NAME = "LAST_PLACE_NAME"
    var LAST_LATITUDE ="LAST_LATITUDE"
    var LAST_LONGITUDE ="LAST_LONGITUDE"
    var LAST_DELIVERY_ADDRESS ="LAST_DELIVERY_ADDRESS"
    var LAST_LANDMARK ="LAST_LANDMARK"
    var LAST_AREA_DETAILS ="LAST_AREA_DETAILS"
}